export type RestartLimit = {
    restartCount: number;
    restartLast: number;
    restartTime: string;
    day: string;
};
export type LoginHeader = {
    "Accept-Language": string;
    Authorization: string;
    "Content-Type": string;
    Connection: string;
    "User-Agent": string;
};
export type RequestHeader = {
    "Content-Type": string;
    "Accept-Language": string;
    Authorization: string;
    Host: string;
    Connection: string;
    "User-Agent": string;
};

export type LoginResponse = {
    access_token: string;
    token_type: string;
    refresh_token: string;
    expires_in: number;
    scope: string;
    tenant_id: number;
    license: string;
    bind_flag: boolean;
    test: number;
    user_id: number;
    refresh_expires_in: number;
    nickname: string | null;
    user_level_code: string;
    active: boolean;
    dept_id: number | null;
    username: string;
    next_token: number;
    next_refreshToken: number;
};

export type LoginError = {
    code: number;
    msg: string;
    data: string;
};

export type DevicesData = {
    deviceId: string;
    smallCutterStatus: number;
    deviceSn: string;
    deviceName: string;
    appUserId: number;
    workStatusCode: number;
    faultStatusCode: string;
    electricity: number;
    wifiLv: number;
    staWifiLv: null | string;
    deviceOnlineFlag: boolean;
    textureMapFlag: number;
    deviceModelId: string;
    deviceModelName: string;
    modelName: string;
    gpsFlag: boolean;
    gpsOnlineFlag: boolean;
    scopeOutside: boolean;
    net4gFlag: boolean;
    net4gStatus: boolean;
    net4gSig: number;
    net4gSigNormal: number;
    picUrl: string;
    picUrlDetail: string;
    commonUse: boolean;
    wirelessWorkStatusCode: number;
    wirelessFaultStatusCode: number;
    firmwareVersion: string;
    firmwareV1Version: string;
    ipAddr: string;
    network: boolean;
    stationOnlineFlag: boolean;
    stationFlag: boolean;
    onConnect: boolean;
    satelliteIntensity: null | string;
    supplierInfo: null | string;
    deviceSpecies: number;
    ownerAppUserId: null | string;
    algoStatus: number;
    topUp: boolean;
    lock: boolean;
    stationSn: null | string;
    wirelessTimeZone: number;
    daylightTimeFlag: boolean;
    rainStatusCode: string;
    net4gCardBindingStatus: boolean;
    rainCountdown: number;
    lat: null | number;
    lng: null | number;
    netConnectType: number;
    hasUnfinishedRegion: null | string;
    filterStatus: number;
    rainFlag: boolean;
    rainDelayLeft: null | string;
    buildMapStatus: number;
    trimmerStatus: null | string;
    taskType: number;
    oneshotTaskType: number;
    smallCutterDiscUrl: null | string;
    smallCutterHeadUrl: null | string;
    trimmerCutterDiscUrl: null | string;
    trimmerCutterHeadUrl: null | string;
    trimmerHasnoCutterDiscUrl: null | string;
    trimmerHasnoCutterHeadUrl: null | string;
};
